language: ruby

addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
env:
  global:
  - PGPORT=5433

services:
  - postgresql

script:
  - bundle exec rails db:drop db:create db:migrate RAILS_ENV=test
  - bundle exec rspec

before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres

rvm:
 - 2.3.6
 - jruby

